#!/usr/bin/env node
/**
 * System telemetry sampler — CPU, memory, GPU (Apple Silicon), and token output.
 *
 * Serves GET /api/system/stats from proxy.js. Nothing here talks to the
 * network except one optional, cached read of Ollama's /api/ps (the model the
 * app is holding in VRAM). All machine readings are no-root:
 *
 *   - System CPU%:  os.cpus() cumulative per-core times sampled every tick.
 *                   (No /proc on macOS, no top child process, no root — this
 *                   is the zero-cost path.)
 *   - App CPU%:     process.cpuUsage() deltas — the proxy's own main-thread
 *                   CPU, attributed as "the app".
 *   - Ollama CPU%:  ps cumulative-CPU-time deltas for processes named
 *                   ollama* — the model backend that drives the GPU.
 *   - GPU:          `ioreg -r -l -w 0 -c AGXAccelerator` → the kernel's own
 *                   PerformanceStatistics dict: Device/Renderer/Tiler
 *                   Utilization % and GPU memory in use. Apple Silicon only;
 *                   on machines without that registry entry `available` is
 *                   false and the UI degrades to CPU+memory+token metrics.
 *   - Memory:       os.totalmem()/os.freemem() + process.memoryUsage().rss.
 *   - Tokens:       recordTokens() is called by the generation paths
 *                   (runToolLoop in proxy.js, turn-controller.js) with the
 *                   streamed deltas. Counts are estimated at ~4 chars/token —
 *                   Ollama does not report eval counts on every chunk — so
 *                   the number is an honest estimate, labelled as such.
 *
 * Every tick pushes a compact sample into a ring buffer (`history`, capped at
 * HISTORY_MAX) so the monitor's running graphic has a backfill even when the
 * tab was not open. The GPU/model reads are async and cached; the tick uses
 * the latest cached value, so it never blocks on a subprocess.
 */

import os from "node:os";
import fs from "node:fs";
import { execFile } from "node:child_process";

const HISTORY_MAX = 240; // ~4 minutes at a 1s tick
const GPU_INTERVAL_MS = 2000;
const MODEL_INTERVAL_MS = 3000;
const MEM_INTERVAL_MS = 2000;

// Cross-device: every machine reading degrades to what the host can report,
// and the snapshot carries explicit availability flags so the UI can hide the
// panels that have nothing to show. `ioreg`/`system_profiler` are Apple-only;
// `ps -axo` works on macOS and Linux but not Windows. os.cpus() and
// process.cpuUsage() work everywhere, so CPU+memory+tokens always render.
const IS_MAC = process.platform === "darwin";
const CAN_USE_PS = process.platform === "darwin" || process.platform === "linux";

const ncpu = Math.max(1, os.cpus().length);

const history = [];

// ── Token accounting ──
const tokenState = {
  total: 0,           // cumulative tokens generated by the engine
  rate: 0,            // tokens/sec over the recent window
  _window: [],        // [{ t, total }] — rate comes from deltas of these
  lastEventAt: 0,
  generating: false,
  lastModel: null,
  genCount: 0,
};

// ── Sampler state ──
let started = false;
let timer = null;
let target = null;
let lastCpuTimes = null;      // per-core { idle, total } from the previous tick
let lastAppCpu = null;        // previous process.cpuUsage()
let lastOllamaCpu = null;     // previous cumulative ollama CPU seconds
let lastTickTs = 0;

const gpu = {
  available: false,
  name: null,
  devicePct: null,
  rendererPct: null,
  tilerPct: null,
  memUsedMb: null,
  ts: 0,
};
let gpuBusy = false;

const model = {
  available: false, // /api/ps answered at least once — distinguishes "no Ollama" from "Ollama, nothing loaded"
  models: [],
  vramMb: 0,
  loaded: null,
  ts: 0,
};

// Memory % cannot be a one-liner: os.freemem() on macOS reports free *pages*,
// and macOS keeps those near zero by pinning everything else in cache, so
// (total - free) reads ~100% used forever. On Linux freemem() is MemFree,
// which excludes page cache, overstating use the same way. The honest reading
// is per-platform: macOS uses vm_stat's active+wired+compressed pages (what
// Activity Monitor calls Memory Used), Linux uses MemAvailable from
// /proc/meminfo, and Windows' freemem is already genuine available memory.
const mem = { pct: null, ts: 0 };

function sampleMem() {
  const total = os.totalmem();
  if (!total) { mem.pct = null; mem.ts = now(); return; }
  if (IS_MAC) {
    execFile("vm_stat", [], { timeout: 2000, maxBuffer: 512 * 1024 }, (err, stdout) => {
      if (!err) {
        const out = String(stdout);
        const m = {};
        for (const line of out.split("\n")) {
          const kv = /^\s*([^:]+):\s+(\d+)/.exec(line);
          if (kv) m[kv[1].trim()] = parseInt(kv[2], 10);
        }
        const ps = (/page size of (\d+) bytes/.exec(out) || [null, 16384])[1];
        const usedBytes = ((m["Pages active"] || 0) + (m["Pages wired down"] || 0) + (m["Pages occupied by compressor"] || 0)) * ps;
        mem.pct = Math.min(100, (usedBytes / total) * 100);
      }
      mem.ts = now();
    });
  } else if (process.platform === "linux") {
    // MemAvailable = free + reclaimable cache — the number that means
    // "if this process asked for RAM right now, this is what's on hand".
    let avail = null;
    try {
      const info = fs.readFileSync("/proc/meminfo", "utf8");
      const m = /MemAvailable:\s+(\d+)/.exec(info);
      if (m) avail = +m[1] * 1024;
    } catch {}
    mem.pct = avail != null ? Math.max(0, Math.min(100, ((total - avail) / total) * 100)) : ((total - os.freemem()) / total) * 100;
    mem.ts = now();
  } else {
    mem.pct = ((total - os.freemem()) / total) * 100;
    mem.ts = now();
  }
}

const now = () => Date.now();

// ── Small parse helpers ──

function parsePsTime(s) {
  // ps -o time gives [[H:]M:]SS(.hh) with centisecond resolution on macOS.
  const m = /^(?:(\d+):)?(\d+):(\d+(?:\.\d+)?)$/.exec(String(s).trim());
  if (!m) return 0;
  const h = m[1] ? +m[1] : 0;
  return h * 3600 + +m[2] * 60 + +m[3];
}

function execP(cmd, args, timeoutMs = 3000) {
  return new Promise((resolve) => {
    execFile(cmd, args, { timeout: timeoutMs, maxBuffer: 2 * 1024 * 1024 }, (err, stdout) => {
      if (err) resolve(null);
      else resolve(String(stdout));
    });
  });
}

// ── GPU read (Apple Silicon only) ──

function readGpu() {
  if (gpuBusy) return;
  if (!IS_MAC) {
    // Not Apple Silicon — ioreg doesn't exist here. Mark permanently
    // unavailable (timestamped so the tick stops re-asking) and let the UI
    // hide the GPU panel via `gpuAvailable: false`.
    if (gpu.available) { gpu.available = false; gpu.devicePct = gpu.rendererPct = gpu.tilerPct = gpu.memUsedMb = null; }
    gpu.ts = now();
    return;
  }
  gpuBusy = true;
  execFile("ioreg", ["-r", "-l", "-w", "0", "-c", "AGXAccelerator"], { timeout: 3000, maxBuffer: 4 * 1024 * 1024 }, (err, stdout) => {
    gpuBusy = false;
    if (err) { gpu.ts = now(); gpu.available = false; return; }
    const out = String(stdout);
    const block = /"PerformanceStatistics"\s*=\s*\{([^}]*)\}/.exec(out);
    if (!gpu.name) {
      gpu.name = /<class\s+(\w+)/.exec(out)?.[1] || "Apple GPU";
    }
    if (!block) { gpu.ts = now(); gpu.available = false; return; }
    const d = {};
    const re = /"([^"]+)"\s*=\s*([^,}]+)/g;
    let kv;
    while ((kv = re.exec(block[1]))) d[kv[1]] = kv[2].trim();
    const num = (k) => { const v = parseFloat(d[k]); return Number.isFinite(v) ? v : null; };
    const memUsed = num("In use system memory (driver)");
    gpu.available = true;
    gpu.devicePct = num("Device Utilization %");
    gpu.rendererPct = num("Renderer Utilization %");
    gpu.tilerPct = num("Tiler Utilization %");
    gpu.memUsedMb = memUsed != null ? Math.round(memUsed / 1048576) : null;
    gpu.ts = now();
  });
}

function fetchSystemName() {
  if (!IS_MAC) return; // system_profiler is Apple-only
  execFile("system_profiler", ["SPDisplaysDataType"], { timeout: 8000, maxBuffer: 2 * 1024 * 1024 }, (err, stdout) => {
    if (!err) {
      const m = /Chipset Model:\s*(.+)/.exec(String(stdout));
      if (m) gpu.name = m[1].trim();
    }
    if (!gpu.name) gpu.name = "Apple GPU";
  });
}

// ── Ollama model-in-VRAM read ──

async function readModel() {
  if (!target) return;
  try {
    const ctrl = new AbortController();
    const to = setTimeout(() => ctrl.abort(), 2500);
    const resp = await fetch(`${target}/api/ps`, { signal: ctrl.signal });
    clearTimeout(to);
    if (!resp.ok) return;
    const data = await resp.json();
    if (data.models == null) return; // unexpected shape — don't mark available
    const ms = (data.models || [])
      .map((x) => ({ name: x.name, vram: x.size_vram || 0 }))
      .filter((x) => x.vram > 0);
    model.models = ms.map((x) => x.name);
    model.vramMb = Math.round(ms.reduce((s, x) => s + x.vram, 0) / 1048576);
    model.loaded = ms[0]?.name || null;
    model.available = true;
    model.ts = now();
  } catch { /* ollama not reachable — keep the last known state */ }
}

// ── Ollama cumulative CPU sampling ──

async function sampleOllamaCpu() {
  if (!CAN_USE_PS) return null; // `ps -axo` is macOS/Linux only (Windows: null → UI hides the line)
  const out = await execP("ps", ["-axo", "comm=,time="], 2500);
  if (out == null) return null;
  let sec = 0;
  for (const line of out.split("\n")) {
    const parts = line.trim().split(/\s+/);
    if (parts.length < 2) continue;
    if (/^ollama/.test(parts[0])) sec += parsePsTime(parts[parts.length - 1]);
  }
  return sec;
}

// ── One tick ──

async function tick() {
  const t = now();
  const dt = (t - lastTickTs) / 1000;

  // System CPU across all cores, from per-core cumulative times.
  const cores = os.cpus().map((c) => c.times);
  const cur = cores.map((c) => ({ idle: c.idle, total: c.user + c.nice + c.sys + c.idle + c.irq }));
  let sysPct = null, cpuCores = null;
  if (lastCpuTimes) {
    let dIdle = 0, dTotal = 0;
    for (let i = 0; i < cores.length; i++) {
      dIdle += cur[i].idle - lastCpuTimes[i].idle;
      dTotal += cur[i].total - lastCpuTimes[i].total;
    }
    if (dTotal > 0) {
      sysPct = (1 - dIdle / dTotal) * 100;          // avg % of one core, 0-100
      cpuCores = ((dTotal - dIdle) / dTotal) * ncpu; // whole-core load, 0..ncpu
    }
  }
  lastCpuTimes = cur;

  // App CPU = this proxy process, main thread.
  const ac = process.cpuUsage();
  let appPct = null;
  if (lastAppCpu && dt > 0) {
    const cpuSec = (ac.user - lastAppCpu.user + ac.system - lastAppCpu.system) / 1e6;
    appPct = (cpuSec / dt) * 100;
  }
  lastAppCpu = ac;

  // Ollama CPU = cumulative-time deltas for the model backend processes.
  let ollamaPct = null;
  const oSec = await sampleOllamaCpu();
  if (oSec != null) {
    if (lastOllamaCpu != null && dt > 0) {
      ollamaPct = Math.max(0, ((oSec - lastOllamaCpu) / dt) * 100);
    }
    lastOllamaCpu = oSec;
  }

  const otherPct = (sysPct != null && appPct != null)
    ? Math.max(0, sysPct - appPct - (ollamaPct || 0))
    : null;

  // Token rate over a ~5s window of tick deltas.
  tokenState._window.push({ t, total: tokenState.total });
  if (tokenState._window.length > 6) tokenState._window.shift();
  tokenState.rate = 0;
  if (tokenState._window.length >= 2) {
    const w0 = tokenState._window[0];
    const w1 = tokenState._window[tokenState._window.length - 1];
    const wdt = (w1.t - w0.t) / 1000;
    if (wdt > 0) tokenState.rate = Math.max(0, (w1.total - w0.total) / wdt);
  }
  if (tokenState.generating && t - tokenState.lastEventAt > 3000) tokenState.generating = false;

  if (t - mem.ts > MEM_INTERVAL_MS) sampleMem();

  history.push({
    t,
    sys: Math.round((sysPct || 0) * 10) / 10,
    app: Math.round((appPct || 0) * 10) / 10,
    ollama: Math.round((ollamaPct || 0) * 10) / 10,
    other: Math.round((otherPct || 0) * 10) / 10,
    cpuCores: Math.round((cpuCores || 0) * 10) / 10,
    gpu: gpu.devicePct,
    mem: mem.pct != null ? Math.round(mem.pct * 10) / 10 : null,
    tok: Math.round(tokenState.rate * 10) / 10,
  });
  if (history.length > HISTORY_MAX) history.shift();
  lastTickTs = t;

  // Async, cached refreshes — never awaited by this tick.
  if (t - gpu.ts > GPU_INTERVAL_MS) readGpu();
  if (t - model.ts > MODEL_INTERVAL_MS) readModel();
}

// ── Public API ──

export function startTelemetry({ target: t, intervalMs = 1000 } = {}) {
  if (started) return;
  started = true;
  target = t || null;
  lastTickTs = now();
  readGpu();
  readModel();
  fetchSystemName();
  sampleMem();
  timer = setInterval(() => { tick().catch(() => {}); }, intervalMs);
  if (typeof timer.unref === "function") timer.unref();
}

export function stopTelemetry() {
  if (timer) clearInterval(timer);
  timer = null;
  started = false;
}

/** The generation paths call this with each streamed text delta. */
export function recordTokens(n, modelName = null) {
  tokenState.total += Math.max(1, Math.round(n || 0));
  tokenState.lastEventAt = now();
  tokenState.generating = true;
  tokenState.genCount += 1;
  if (modelName) tokenState.lastModel = modelName;
}

/** Called when a generation call completes, so the live "generating" flag
 *  drops promptly instead of waiting out the 3s idle timeout. */
export function endGeneration() {
  tokenState.generating = false;
}

export function systemSnapshot() {
  const last = history[history.length - 1] || null;
  const memTotal = os.totalmem();
  return {
    ts: now(),
    uptime: process.uptime(),
    ncpu,
    gpuAvailable: gpu.available,
    gpuName: gpu.name,
    system: {
      cpuPct: last?.sys ?? null,
      cpuCores: last?.cpuCores ?? null,
      memPct: last?.mem ?? null,
      memTotalMb: Math.round(memTotal / 1048576),
    },
    app: {
      cpuPct: last?.app ?? null,
      rssMb: Math.round(process.memoryUsage().rss / 1048576),
      generating: tokenState.generating,
    },
    ollama: {
      available: model.available,
      cpuAvailable: last?.ollama != null,
      cpuPct: last?.ollama ?? null,
      models: model.models,
      vramMb: model.vramMb,
      loaded: model.loaded,
    },
    other: { cpuPct: last?.other ?? null },
    gpu: {
      devicePct: gpu.devicePct,
      rendererPct: gpu.rendererPct,
      tilerPct: gpu.tilerPct,
      memUsedMb: gpu.memUsedMb,
    },
    tokens: {
      total: tokenState.total,
      rate: Math.round(tokenState.rate * 10) / 10,
      generating: tokenState.generating,
      lastModel: tokenState.lastModel,
    },
    history: history.slice(),
  };
}

export function tokensStats() {
  return { ...tokenState };
}
